export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'primary': '#515d84',
        'primary-dim': '#455177',
        'primary-fixed': '#dbe1ff',
        'primary-fixed-dim': '#c7d3ff',
        'primary-container': '#dbe1ff',
        'on-primary': '#f8f7ff',
        'on-primary-container': '#445076',
        'on-primary-fixed': '#313e63',
        'on-primary-fixed-variant': '#4e5a81',
        'inverse-primary': '#c4d0fd',
        'secondary': '#4d626c',
        'secondary-dim': '#415660',
        'secondary-fixed': '#cfe6f2',
        'secondary-fixed-dim': '#c1d8e4',
        'secondary-container': '#cfe6f2',
        'on-secondary': '#f2faff',
        'on-secondary-container': '#40555f',
        'on-secondary-fixed': '#2d424c',
        'on-secondary-fixed-variant': '#495f69',
        'tertiary': '#545f78',
        'tertiary-dim': '#49536b',
        'tertiary-fixed': '#d5dffd',
        'tertiary-fixed-dim': '#c7d1ee',
        'tertiary-container': '#d5dffd',
        'on-tertiary': '#f9f8ff',
        'on-tertiary-container': '#455068',
        'on-tertiary-fixed': '#333d55',
        'on-tertiary-fixed-variant': '#4f5a72',
        'background': '#f8f9fb',
        'on-background': '#2a3439',
        'surface': '#f8f9fb',
        'surface-dim': '#cfdce3',
        'surface-bright': '#f8f9fb',
        'surface-tint': '#515d84',
        'surface-variant': '#d9e4ea',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f0f4f7',
        'surface-container': '#e8eff3',
        'surface-container-high': '#e1e9ee',
        'surface-container-highest': '#d9e4ea',
        'on-surface': '#2a3439',
        'on-surface-variant': '#566166',
        'inverse-surface': '#0b0f10',
        'inverse-on-surface': '#9a9d9f',
        'outline': '#717c82',
        'outline-variant': '#a9b4b9',
        'error': '#9e3f4e',
        'error-dim': '#4f0116',
        'error-container': '#ff8b9a',
        'on-error': '#fff7f7',
        'on-error-container': '#782232',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        '2xl': '1rem',
        full: '0.75rem',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
}